ALTER TABLE Tweet DROP CONSTRAINT FKTweet155392;
ALTER TABLE Tweet DROP CONSTRAINT FKTweet291268;
DROP TABLE IF EXISTS Moderator CASCADE;
DROP TABLE IF EXISTS Stations CASCADE;
DROP TABLE IF EXISTS Tweet CASCADE;

