ALTER TABLE Bericht DROP CONSTRAINT FKBericht515760;
ALTER TABLE Bericht DROP CONSTRAINT FKBericht241876;
DROP TABLE IF EXISTS Bericht CASCADE;
DROP TABLE IF EXISTS Moderator CASCADE;
DROP TABLE IF EXISTS Stations CASCADE;

