ALTER TABLE Aankoop DROP CONSTRAINT FKAankoop554580;
ALTER TABLE Aankoop DROP CONSTRAINT FKAankoop426516;
ALTER TABLE Transactie DROP CONSTRAINT FKTransactie507746;
ALTER TABLE Transactie DROP CONSTRAINT FKTransactie647021;
DROP TABLE IF EXISTS Aankoop CASCADE;
DROP TABLE IF EXISTS Bonuskaart CASCADE;
DROP TABLE IF EXISTS Filiaal CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Transactie CASCADE;

